[package]
name = "egui_template"
version = "0.1.0"
authors = ["Emil Ernerfeldt <emil.ernerfeldt@gmail.com>", "Yan Chubikov <yan.gyunashyan@gmail.com>"]

[dependencies]
# GUI
egui = "0.18.0"
eframe = "0.18.0"

# Other